INCLUDE 'EMU8086.INC'
.MODEL SMALL
.STACK 100H
.DATA
A DW ?
.CODE
MAIN PROC
    
    PRINT 'ENTER YOUR FIRST NUMBER : '

    CALL SCAN_NUM
    MOV AX, CX
    PRINTN
    PRINT 'ENTER YOUR 2ND NUMBER : '

    CALL SCAN_NUM
    ADD AX, CX
    PRINTN
    PRINT 'YOU HAVE ENTERED: '
    CALL PRINT_NUM
    
    EXIT:
    MOV AH,4CH
    INT 21H
    
    MAIN ENDP
    DEFINE_SCAN_NUM
    
    DEFINE_PRINT_NUM
    DEFINE_PRINT_NUM_UNS
END MAIN